### ISSUE TITLE
orkl and solo

### ISSUE THREAD

**Issue by kodedninja** [new-computers/guides#6]
I don't want to self-advertise here, but I do think [orkl](https://github.com/kodedninja/orkl) and [solo](https:/github.com/kodedninja/solo) are two simple solutions for p2p publishing, next to Enoki. 

They're a lot smaller, but sometimes they provide a simpler UX for small pieces of content. :smile:

**Comment by callil** [comment]
I would love to see some guides and documentation for these tools!
